### PR TITLE
Guide on Git by Purvi singh

### PR DESCRIPTION
**Pull request by Purvi-102**

### CODE REVIEW

**Comment by deepak2431** [comment]
Please update the content.

**Comment by deepak2431** [comment]
Why so less content just 45 lines. Please improve it.

**Comment by Purvi-102** [comment]
Sir i have added detailed description about merge conflicts and how to
resolve them , what are branches, how can we delete a branch and a
difference between delete commands and add a little description on git also

**Comment by deepak2431** [comment]
Why txt files it should be markdown. Please fix that issue.

**Comment by Purvi-102** [comment]
Done sir

**Pull request merged**
